FIX Grafana dashboards files are stored in a bad format
canonical/grafana-agent-k8s-operator pull request #139
Opened 2023-03-17 18:28 UTC by Abuelodelanada

## Issue

This PR fixes #135 

## Solution

This PR fixes:
- The dashboard's malformed files names
- Dashboards content: There is no need to transform the content of the dashboard, since the [lib returns a string](https://github.com/canonical/grafana-agent-k8s-operator/blob/machine_charm/lib/charms/grafana_agent/v0/cos_agent.py#L475)
- Files overwrite: As we generated the same name, the files were overwritten.

2023-03-17 18:36 UTC, sed-i approved these changes
Would be nice to add some comments.
The code is quite opaque with regards to the underlying data structure.

2023-03-17 20:19 UTC, Abuelodelanada commented on src/grafana_agent.py
> +        for dash in enumerate(dashboards):
done

2023-03-17 23:40 UTC, rbarry82 requested changes
Copying from MM because it deserves a little thought. Feel free to dismiss once read (no actual changes _required_, but I'm not convinced that adding the key/enum in the filename is a good long term idea, and as a subordinate, it doesn't offer much advantage when we already have the rel id and charm name). There's a reasonably high risk of getting duplicate dashboards this way, even from the same charm if a refreshed version enumerates differently and the content hash differs.

[This](https://github.com/canonical/grafana-agent-k8s-operator/pull/139/files) looks familiar @jose-masson -- I pushed up a [really similar one](https://github.com/canonical/grafana-agent-k8s-operator/pull/136/files) last night once I look at the code again :rolling_on_the_floor_laughing: 

I'm happy to use yours with a little less code golfing in f-strings than mine. The enumeration of `List[Dict[str, str]]` is just gonna give some int as `key`, though. Considering it's a subordinate and we already included the rel id, do we really think we need it? Or, if it's just an int, do we want to make it `idx` or something?

I'm not against the idea, but Grafana goes _a little_ further into checking what's inside files than the rules format/dedupe. I do wonder whether including the enumeration ID as part of the filename will do bad things. Grafana had to fight a lot in the beginning with limitations on cmdline length given how many operations it pushed (including `_stored.foo = ...`, which actually called `juju set-state ...` via subprocess), and it keeps track of dashboards read from disk, partly, [via `path.stem`](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1137).

If the loading of dashboards/enumerating doesn't return the same order in the list every time, we may end up with the "same" dashboard with different iterator IDs, and GrafanaDashboardProvider won't "know" they're the same. I don't think Juju guarantees list ordering (or really, it's unmarshaling strings, but I should say that I don't know if `json.loads(json.dumps(some_dict))` has any guarantees around ordering).

Not blocking on it, but it's worth asking how much value it adds for a subordinate

2023-03-20 04:48 UTC, Abuelodelanada commented
Hi @rbarry82 

Thanks for the review!

I don't think I quite understand you.

About these:
> Considering it's a subordinate and we already included the rel id, do we really think we need it? 


> I do wonder whether including the enumeration ID as part of the filename will do bad things. 

The answer is Yes.
We do need the ID as part of the filename. In fact what we need is a way to create unique file names. Otherwise if the charm provides more than one dashboard, we'll end up overwriting the dashboards because the generated filenames are the same. That's why I include the `key`.
Note that in the original code, we generate the same file name for every dashboard.
 
Regarding this:

> If the loading of dashboards/enumerating doesn't return the same order in the list every time, we may end up with the "same" dashboard with different iterator IDs, and GrafanaDashboardProvider won't "know" they're the same.

As far as I understand, every time there is a `_cos.on.data_changed` event, Grafana Agent will remove and re-generate the dashboards files stored in `/var/lib/juju/agents/unit-grafana-agent-{NUM}/charm/grafana_dashboards`, after that the method [`_update_all_dashboards_from_dir`](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1114) will be executed. This method [delete](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1128) the previous stored dashboard files from `self._stored` and [re-store](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1138) them.

2023-03-20 11:15 UTC, rbarry82 commented
> The answer is Yes. We do need the ID as part of the filename. In fact what we need is a way to create unique file names. Otherwise if the charm provides more than one dashboard, we'll end up overwriting the dashboards because the generated filenames are the same. That's why I include the `key`. Note that in the original code, we generate the same file name for every dashboard.

Can we use the hash for this, as we do for `_generate_alt_uid` or otherwise sum it? Even that may not be reliable if the content changes, but using `dashboard["title"].replace(" ", "_").lower()` would be "same title -> same filename", and put the name of the dashboard in the filename, too.

> > If the loading of dashboards/enumerating doesn't return the same order in the list every time, we may end up with the "same" dashboard with different iterator IDs, and GrafanaDashboardProvider won't "know" they're the same.
> 
> As far as I understand, every time there is a `_cos.on.data_changed` event, Grafana Agent will remove and re-generate the dashboards files stored in `/var/lib/juju/agents/unit-grafana-agent-{NUM}/charm/grafana_dashboards`, after that the method [`_update_all_dashboards_from_dir`](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1114) will be executed. This method [delete](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1128) the previous stored dashboard files from `self._stored` and [re-store](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1138) them.

Yes, but the line I'm worried about that is [two above what was linked](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1126) and [just below it](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1137). Unlike other charms (due, again, mostly to the limitations in subprocess from sending huge amounts of data during `set-state` for relation data) Grafana does not wipe the entire list. It only deletes matched keys, and that key [includes `filename.stem`](https://github.com/canonical/grafana-k8s-operator/blob/main/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1137), which will include the enumerated index.

That's why I'm worried that a charm refresh/update which, say, adds a dashboard, or a lack of a guarantee in ordering after serializing/de-serializing the list to put it into relation data will result in `juju_0_....json` being renamed/changed to `juju_1_....json` if something changes, and then we wouldn't end up with the behavior we want.

2023-03-20 15:30 UTC, rbarry82 commented
> > Can we use the hash for this, as we do for `_generate_alt_uid` or otherwise sum it? Even that may not be reliable if the content changes, but using `dashboard["title"].replace(" ", "_").lower()` would be "same title -> same filename", and put the name of the dashboard in the filename, too.
> 
> This could be a solution... I did not implement the hash, since I thought with the key was enough. Thanks!

Assuming that the ordering is the same, but.. I don't think that's a great guarantee either.

Honestly, using a hash potentially has the same risk if the "same dashboard" ends up changing enough that the hash is meaningfully different. Using `dashboard["title"]....` is probably the closest we'll get to "if this dashboard is updated on upgrade, replace the old one" until we have time to test whether OF not sending relation stuff over subprocess anymore makes it safe for Grafana to drop all of the storedstate stuff that's happening right now.

2023-03-20 20:13 UTC, merged